Repository minio/mc, pull requests merged in 2024-05, with the labels that each got.

#4920 Added test for bucket replication
  functional-tests.sh
Labels: needs review, new feature

#4924 Correct spelling in message
  .github/workflows/vulncheck.yml
  cmd/encrypt-info.go
Labels: bugfix, needs review

#4922 fix replication bandwidth unit conversion
  cmd/admin-bucket-remote-add_test.go
  cmd/admin-replicate-info.go
  cmd/admin-replicate-update.go
  cmd/replicate-add.go
  cmd/replicate-status.go
  cmd/replicate-update.go
Labels: bugfix, needs review

#4923 fix: mirror --summary should work like -q
  cmd/mirror-main.go
Labels: bugfix, needs review

#4935 simplify histograms, make it based on the server return
  cmd/stat.go
Labels: bugfix
