Repository minio/mc, pull requests merged in 2024-01, with the labels that each got.

#4812 Length check for alias
  cmd/config.go
Labels: do not close

#4831 feat: add skip-errors to mc mirror
  cmd/mirror-main.go
  cmd/mirror-url.go
Labels: bugfix

#4834 Fix syntax in examples
  cmd/anonymous-main.go
Labels: community, bugfix

#4825 fix: mirror with local path
  cmd/difference_test.go
  cmd/mirror-main.go
  cmd/mirror-url.go
Labels: bugfix, needs review
