Repository minio/mc, pull requests merged in 2024-03, with the labels that each got.

#4864 replicate: support alias
  cmd/replicate-add.go
  cmd/replicate-update.go
Labels: community, new feature

#4861 mirror: add bucket exclusions
  cmd/mirror-main.go
  cmd/mirror-url.go
Labels: community

#4859 mc support commands: allow --json in online mode
  cmd/license-info.go
  cmd/license-register.go
  cmd/license-unregister.go
  cmd/subnet-utils.go
  cmd/support-diag.go
  cmd/support-inspect.go
  cmd/support-perf.go
  cmd/support-profile.go
  cmd/support-proxy-remove.go
  cmd/support-proxy-set.go
  cmd/support-proxy-show.go
  cmd/support.go
Labels: new feature

#4854 Add command for uploading file to SUBNET issue
  cmd/auto-complete.go
  cmd/subnet-utils.go
  cmd/support-diag.go
  cmd/support-inspect.go
  cmd/support-perf.go
  cmd/support-profile.go
  cmd/support-upload.go
  cmd/support.go
Labels: new feature

#4885 Expose health diagnostics related functions
  cmd/globals.go
  cmd/license-update.go
  cmd/subnet-file-uploader.go
  cmd/subnet-utils.go
  cmd/subnet-utils_test.go
  cmd/support-diag.go
  cmd/support-inspect.go
  cmd/support-perf.go
  cmd/support-profile.go
  cmd/support-upload.go
  cmd/support.go
Labels: new feature

#4877 Functional tests: add a parameter for the full site cleaning test
  functional-tests.sh
Labels: community, bugfix

#4867 doc update
  docs/minio-admin-complete-guide.md
  docs/minio-client-complete-guide.md
Labels: community, needs review
