Repository minio/mc, pull requests merged in 2024-02, with the labels that each got.

#4843 Removing terminal whitelist for pager mechanism
  cmd/globals.go
  cmd/main.go
Labels: bugfix, needs review

#4845 fix missing space while printing profile success message
  cmd/support-profile.go
Labels: bugfix

#4842 mirror:copy events also can mirror
  cmd/mirror-main.go
Labels: community

#4846 fix example in admin replicate update
  cmd/admin-replicate-update.go
Labels: bugfix, needs review

#4839 feat: add put action
  cmd/auto-complete.go
  cmd/cat-main.go
  cmd/client-s3.go
  cmd/client-url.go
  cmd/client.go
  cmd/common-methods.go
  cmd/cp-main.go
  cmd/cp-url.go
  cmd/diff-main.go
  cmd/du-main.go
  cmd/find-main.go
  cmd/main.go
  cmd/mirror-main.go
  cmd/mirror-url.go
  cmd/put-main.go
  cmd/put-url.go
  cmd/rm-main.go
  cmd/share-download-main.go
  cmd/sql-main.go
  cmd/stat-main.go
  cmd/stat.go
  cmd/tree-main.go
Labels: new feature

#4840 Enable --expire-all-object-versions
  cmd/ilm-rule-add.go
  cmd/ilm/options.go
  cmd/ilm/parse.go
  go.mod
  go.sum
Labels: new feature

#4847 feat: add mc get
  cmd/auto-complete.go
  cmd/common-methods.go
  cmd/cp-main.go
  cmd/get-main.go
  cmd/get-url.go
  cmd/main.go
Labels: needs review, new feature
