Repository minio/mc, pull requests merged in 2025-05, with the labels that each got.

#5194 Explicitly set file permissions for admin-cluster-{bucket,iam}-export…
  cmd/admin-cluster-bucket-export.go
  cmd/admin-cluster-iam-export.go
Labels: enhancement, community

#5202 Add STATUS column to batch job list table output
  cmd/batch-list.go
Labels: community, needs review

#5205 Fix deletion of previously sync'd buckets and objects during mc-mirror
  cmd/mirror-main.go
Labels: bugfix
